site_name: PySiddhi
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
  - Welcome to PySiddhi: index.md
  - License: license.md
  - Installation-Guide : Installation-Guide.md
  - Demos :
    - For Siddhi 4: Quick-Demo-(PySiddhi4).md
    - For Stream Processor 4: Quick-Demo-(SP4).md
  - Siddhi Java to Python Mapping: Using-Siddhi-from-Python.md
  - Siddhi App Management using Python Client: Siddhi-App-Management-of-WSO2-SP-4.md
  - Using Event Simulator : Event-Simulator-of-SP-4.md
theme: material