site_name: PySiddhi
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
  - Welcome to PySiddhi: index.md
  - License: license.md
  - Installation Guide: Installation-Guide.md
  - Run PySiddhi4: Quick-Demo-(PySiddhi4).md
  - Advanced Concepts of PySiddhi: Using-Siddhi-from-Python.md
  - PySiddhi Client to Manage WSO2 Stream Processor: Quick-Demo-(SP4).md
    - Client APIs to Manage Siddhi App: Siddhi-App-Management-of-WSO2-SP-4.md
    - Client APIs to Simulate Events: Event-Simulator-of-SP-4.md
theme: material